SET SQL_SAFE_UPDATES = 0;

START TRANSACTION;

UPDATE products SET name = 'Velvety Dark Chocolate - Peru 58%', origin = 'Peru', slug = 'velvety-dark-chocolate-peru-58-80g' WHERE id = 1;
UPDATE products SET name = 'Roasted Milk Chocolate - Ecuador 61%', origin = 'Ecuador', slug = 'roasted-milk-chocolate-ecuador-61-90g' WHERE id = 2;
UPDATE products SET name = 'Hand-Tempered White Chocolate - Madagascar 64%', origin = 'Madagascar', slug = 'hand-tempered-white-chocolate-madagascar-64-100g' WHERE id = 3;
UPDATE products SET name = 'Single-Harvest Ruby Chocolate - Venezuela 67%', origin = 'Venezuela', slug = 'single-harvest-ruby-chocolate-venezuela-67-110g' WHERE id = 4;
UPDATE products SET name = 'Stone-Ground Filled & Pralines - Ghana 70%', origin = 'Ghana', slug = 'stone-ground-filled-and-pralines-ghana-70-70g' WHERE id = 5;
UPDATE products SET name = 'Silk-Smooth Drinking Chocolate - Colombia 73%', origin = 'Colombia', slug = 'silk-smooth-drinking-chocolate-colombia-73-80g' WHERE id = 6;
UPDATE products SET name = 'Cacao-Rich Vegan & Dairy-Free - Mexico 76%', origin = 'Mexico', slug = 'cacao-rich-vegan-and-dairy-free-mexico-76-90g' WHERE id = 7;
UPDATE products SET name = 'Midnight Sugar-Free - Dominican Republic 79%', origin = 'Dominican Republic', slug = 'midnight-sugar-free-dominican-republic-79-100g' WHERE id = 8;
UPDATE products SET name = 'Amber Single Origin - Ivory Coast 82%', origin = 'Ivory Coast', slug = 'amber-single-origin-ivory-coast-82-110g' WHERE id = 9;
UPDATE products SET name = 'Luxe Seasonal & Limited Edition - Brazil 85%', origin = 'Brazil', slug = 'luxe-seasonal-and-limited-edition-brazil-85-70g' WHERE id = 10;
UPDATE products SET name = 'Golden Gift Boxes - Madagascar 88%', origin = 'Madagascar', slug = 'golden-gift-boxes-madagascar-88-80g' WHERE id = 11;
UPDATE products SET name = 'Estate Spreads & Creams - Madagascar 91%', origin = 'Madagascar', slug = 'estate-spreads-and-creams-madagascar-91-90g' WHERE id = 12;
UPDATE products SET name = 'Vintage Raw & Organic - Vietnam 94%', origin = 'Vietnam', slug = 'vintage-raw-and-organic-vietnam-94-100g' WHERE id = 13;
UPDATE products SET name = 'Signature Chocolate-Covered Nuts - Philippines 57%', origin = 'Philippines', slug = 'signature-chocolate-covered-nuts-philippines-57-110g' WHERE id = 14;
UPDATE products SET name = 'Artisan Chocolate Bars - Tanzania 60%', origin = 'Tanzania', slug = 'artisan-chocolate-bars-tanzania-60-70g' WHERE id = 15;
UPDATE products SET name = 'Velvety Dark Chocolate - Ecuador 63%', origin = 'Ecuador', slug = 'velvety-dark-chocolate-ecuador-63-80g' WHERE id = 16;
UPDATE products SET name = 'Roasted Milk Chocolate - Peru 66%', origin = 'Peru', slug = 'roasted-milk-chocolate-peru-66-90g' WHERE id = 17;
UPDATE products SET name = 'Hand-Tempered White Chocolate - Dominican Republic 69%', origin = 'Dominican Republic', slug = 'hand-tempered-white-chocolate-dominican-republic-69-100g' WHERE id = 18;
UPDATE products SET name = 'Single-Harvest Ruby Chocolate - Peru 72%', origin = 'Peru', slug = 'single-harvest-ruby-chocolate-peru-72-110g' WHERE id = 19;
UPDATE products SET name = 'Stone-Ground Filled & Pralines - Ecuador 75%', origin = 'Ecuador', slug = 'stone-ground-filled-and-pralines-ecuador-75-70g' WHERE id = 20;
UPDATE products SET name = 'Silk-Smooth Drinking Chocolate - Mexico 78%', origin = 'Mexico', slug = 'silk-smooth-drinking-chocolate-mexico-78-80g' WHERE id = 21;
UPDATE products SET name = 'Cacao-Rich Vegan & Dairy-Free - Peru 81%', origin = 'Peru', slug = 'cacao-rich-vegan-and-dairy-free-peru-81-90g' WHERE id = 22;
UPDATE products SET name = 'Midnight Sugar-Free - Peru 84%', origin = 'Peru', slug = 'midnight-sugar-free-peru-84-100g' WHERE id = 23;
UPDATE products SET name = 'Amber Single Origin - Peru 87%', origin = 'Peru', slug = 'amber-single-origin-peru-87-110g' WHERE id = 24;
UPDATE products SET name = 'Luxe Seasonal & Limited Edition - Peru 90%', origin = 'Peru', slug = 'luxe-seasonal-and-limited-edition-peru-90-70g' WHERE id = 25;
UPDATE products SET name = 'Golden Gift Boxes - Madagascar 93%', origin = 'Madagascar', slug = 'golden-gift-boxes-madagascar-93-80g' WHERE id = 26;
UPDATE products SET name = 'Estate Spreads & Creams - Madagascar 56%', origin = 'Madagascar', slug = 'estate-spreads-and-creams-madagascar-56-90g' WHERE id = 27;
UPDATE products SET name = 'Vintage Raw & Organic - Vietnam 59%', origin = 'Vietnam', slug = 'vintage-raw-and-organic-vietnam-59-100g' WHERE id = 28;
UPDATE products SET name = 'Signature Chocolate-Covered Nuts - Peru 62%', origin = 'Peru', slug = 'signature-chocolate-covered-nuts-peru-62-110g' WHERE id = 29;
UPDATE products SET name = 'Artisan Chocolate Bars - Peru 65%', origin = 'Peru', slug = 'artisan-chocolate-bars-peru-65-70g' WHERE id = 30;
UPDATE products SET name = 'Velvety Dark Chocolate - Madagascar 68%', origin = 'Madagascar', slug = 'velvety-dark-chocolate-madagascar-68-80g' WHERE id = 31;
UPDATE products SET name = 'Roasted Milk Chocolate - Madagascar 71%', origin = 'Madagascar', slug = 'roasted-milk-chocolate-madagascar-71-90g' WHERE id = 32;
UPDATE products SET name = 'Hand-Tempered White Chocolate - Peru 74%', origin = 'Peru', slug = 'hand-tempered-white-chocolate-peru-74-100g' WHERE id = 33;
UPDATE products SET name = 'Single-Harvest Ruby Chocolate - Ecuador 77%', origin = 'Ecuador', slug = 'single-harvest-ruby-chocolate-ecuador-77-110g' WHERE id = 34;
UPDATE products SET name = 'Stone-Ground Filled & Pralines - Peru 80%', origin = 'Peru', slug = 'stone-ground-filled-and-pralines-peru-80-70g' WHERE id = 35;
UPDATE products SET name = 'Silk-Smooth Drinking Chocolate - Peru 83%', origin = 'Peru', slug = 'silk-smooth-drinking-chocolate-peru-83-80g' WHERE id = 36;
UPDATE products SET name = 'Cacao-Rich Vegan & Dairy-Free - Ecuador 86%', origin = 'Ecuador', slug = 'cacao-rich-vegan-and-dairy-free-ecuador-86-90g' WHERE id = 37;
UPDATE products SET name = 'Midnight Sugar-Free - Ecuador 89%', origin = 'Ecuador', slug = 'midnight-sugar-free-ecuador-89-100g' WHERE id = 38;
UPDATE products SET name = 'Amber Single Origin - Ecuador 92%', origin = 'Ecuador', slug = 'amber-single-origin-ecuador-92-110g' WHERE id = 39;
UPDATE products SET name = 'Luxe Seasonal & Limited Edition - Madagascar 55%', origin = 'Madagascar', slug = 'luxe-seasonal-and-limited-edition-madagascar-55-70g' WHERE id = 40;
UPDATE products SET name = 'Golden Gift Boxes - Madagascar 58%', origin = 'Madagascar', slug = 'golden-gift-boxes-madagascar-58-80g' WHERE id = 41;
UPDATE products SET name = 'Estate Spreads & Creams - Madagascar 61%', origin = 'Madagascar', slug = 'estate-spreads-and-creams-madagascar-61-90g' WHERE id = 42;
UPDATE products SET name = 'Vintage Raw & Organic - Vietnam 64%', origin = 'Vietnam', slug = 'vintage-raw-and-organic-vietnam-64-100g' WHERE id = 43;
UPDATE products SET name = 'Signature Chocolate-Covered Nuts - Ecuador 67%', origin = 'Ecuador', slug = 'signature-chocolate-covered-nuts-ecuador-67-110g' WHERE id = 44;
UPDATE products SET name = 'Artisan Chocolate Bars - Ecuador 70%', origin = 'Ecuador', slug = 'artisan-chocolate-bars-ecuador-70-70g' WHERE id = 45;
UPDATE products SET name = 'Velvety Dark Chocolate - Venezuela 73%', origin = 'Venezuela', slug = 'velvety-dark-chocolate-venezuela-73-80g' WHERE id = 46;
UPDATE products SET name = 'Roasted Milk Chocolate - Dominican Republic 76%', origin = 'Dominican Republic', slug = 'roasted-milk-chocolate-dominican-republic-76-90g' WHERE id = 47;
UPDATE products SET name = 'Hand-Tempered White Chocolate - Ecuador 79%', origin = 'Ecuador', slug = 'hand-tempered-white-chocolate-ecuador-79-100g' WHERE id = 48;
UPDATE products SET name = 'Single-Harvest Ruby Chocolate - Madagascar 82%', origin = 'Madagascar', slug = 'single-harvest-ruby-chocolate-madagascar-82-110g' WHERE id = 49;
UPDATE products SET name = 'Stone-Ground Filled & Pralines - Madagascar 85%', origin = 'Madagascar', slug = 'stone-ground-filled-and-pralines-madagascar-85-70g' WHERE id = 50;
UPDATE products SET name = 'Silk-Smooth Drinking Chocolate - Ecuador 88%', origin = 'Ecuador', slug = 'silk-smooth-drinking-chocolate-ecuador-88-80g' WHERE id = 51;
UPDATE products SET name = 'Cacao-Rich Vegan & Dairy-Free - Dominican Republic 91%', origin = 'Dominican Republic', slug = 'cacao-rich-vegan-and-dairy-free-dominican-republic-91-90g' WHERE id = 52;
UPDATE products SET name = 'Midnight Sugar-Free - Colombia 94%', origin = 'Colombia', slug = 'midnight-sugar-free-colombia-94-100g' WHERE id = 53;
UPDATE products SET name = 'Amber Single Origin - Madagascar 57%', origin = 'Madagascar', slug = 'amber-single-origin-madagascar-57-110g' WHERE id = 54;
UPDATE products SET name = 'Luxe Seasonal & Limited Edition - Ecuador 60%', origin = 'Ecuador', slug = 'luxe-seasonal-and-limited-edition-ecuador-60-70g' WHERE id = 55;
UPDATE products SET name = 'Golden Gift Boxes - Madagascar 63%', origin = 'Madagascar', slug = 'golden-gift-boxes-madagascar-63-80g' WHERE id = 56;
UPDATE products SET name = 'Estate Spreads & Creams - Madagascar 66%', origin = 'Madagascar', slug = 'estate-spreads-and-creams-madagascar-66-90g' WHERE id = 57;
UPDATE products SET name = 'Vintage Raw & Organic - Vietnam 69%', origin = 'Vietnam', slug = 'vintage-raw-and-organic-vietnam-69-100g' WHERE id = 58;
UPDATE products SET name = 'Signature Chocolate-Covered Nuts - Colombia 72%', origin = 'Colombia', slug = 'signature-chocolate-covered-nuts-colombia-72-110g' WHERE id = 59;
UPDATE products SET name = 'Artisan Chocolate Bars - Madagascar 75%', origin = 'Madagascar', slug = 'artisan-chocolate-bars-madagascar-75-70g' WHERE id = 60;
UPDATE products SET name = 'Velvety Dark Chocolate - Ghana 78%', origin = 'Ghana', slug = 'velvety-dark-chocolate-ghana-78-80g' WHERE id = 61;
UPDATE products SET name = 'Roasted Milk Chocolate - Colombia 81%', origin = 'Colombia', slug = 'roasted-milk-chocolate-colombia-81-90g' WHERE id = 62;
UPDATE products SET name = 'Hand-Tempered White Chocolate - Mexico 84%', origin = 'Mexico', slug = 'hand-tempered-white-chocolate-mexico-84-100g' WHERE id = 63;
UPDATE products SET name = 'Single-Harvest Ruby Chocolate - Brazil 87%', origin = 'Brazil', slug = 'single-harvest-ruby-chocolate-brazil-87-110g' WHERE id = 64;
UPDATE products SET name = 'Stone-Ground Filled & Pralines - Colombia 90%', origin = 'Colombia', slug = 'stone-ground-filled-and-pralines-colombia-90-70g' WHERE id = 65;
UPDATE products SET name = 'Silk-Smooth Drinking Chocolate - Ghana 93%', origin = 'Ghana', slug = 'silk-smooth-drinking-chocolate-ghana-93-80g' WHERE id = 66;
UPDATE products SET name = 'Cacao-Rich Vegan & Dairy-Free - Colombia 56%', origin = 'Colombia', slug = 'cacao-rich-vegan-and-dairy-free-colombia-56-90g' WHERE id = 67;
UPDATE products SET name = 'Midnight Sugar-Free - Madagascar 59%', origin = 'Madagascar', slug = 'midnight-sugar-free-madagascar-59-100g' WHERE id = 68;
UPDATE products SET name = 'Amber Single Origin - Venezuela 62%', origin = 'Venezuela', slug = 'amber-single-origin-venezuela-62-110g' WHERE id = 69;
UPDATE products SET name = 'Luxe Seasonal & Limited Edition - Colombia 65%', origin = 'Colombia', slug = 'luxe-seasonal-and-limited-edition-colombia-65-70g' WHERE id = 70;
UPDATE products SET name = 'Golden Gift Boxes - Madagascar 68%', origin = 'Madagascar', slug = 'golden-gift-boxes-madagascar-68-80g' WHERE id = 71;
UPDATE products SET name = 'Estate Spreads & Creams - Madagascar 71%', origin = 'Madagascar', slug = 'estate-spreads-and-creams-madagascar-71-90g' WHERE id = 72;
UPDATE products SET name = 'Vintage Raw & Organic - Vietnam 74%', origin = 'Vietnam', slug = 'vintage-raw-and-organic-vietnam-74-100g' WHERE id = 73;
UPDATE products SET name = 'Signature Chocolate-Covered Nuts - Madagascar 77%', origin = 'Madagascar', slug = 'signature-chocolate-covered-nuts-madagascar-77-110g' WHERE id = 74;
UPDATE products SET name = 'Artisan Chocolate Bars - Ghana 80%', origin = 'Ghana', slug = 'artisan-chocolate-bars-ghana-80-70g' WHERE id = 75;
UPDATE products SET name = 'Velvety Dark Chocolate - Colombia 83%', origin = 'Colombia', slug = 'velvety-dark-chocolate-colombia-83-80g' WHERE id = 76;
UPDATE products SET name = 'Roasted Milk Chocolate - Brazil 86%', origin = 'Brazil', slug = 'roasted-milk-chocolate-brazil-86-90g' WHERE id = 77;
UPDATE products SET name = 'Hand-Tempered White Chocolate - Brazil 89%', origin = 'Brazil', slug = 'hand-tempered-white-chocolate-brazil-89-100g' WHERE id = 78;
UPDATE products SET name = 'Single-Harvest Ruby Chocolate - Colombia 92%', origin = 'Colombia', slug = 'single-harvest-ruby-chocolate-colombia-92-110g' WHERE id = 79;
UPDATE products SET name = 'Stone-Ground Filled & Pralines - Venezuela 55%', origin = 'Venezuela', slug = 'stone-ground-filled-and-pralines-venezuela-55-70g' WHERE id = 80;
UPDATE products SET name = 'Silk-Smooth Drinking Chocolate - Madagascar 58%', origin = 'Madagascar', slug = 'silk-smooth-drinking-chocolate-madagascar-58-80g' WHERE id = 81;
UPDATE products SET name = 'Cacao-Rich Vegan & Dairy-Free - Ghana 61%', origin = 'Ghana', slug = 'cacao-rich-vegan-and-dairy-free-ghana-61-90g' WHERE id = 82;
UPDATE products SET name = 'Midnight Sugar-Free - Brazil 64%', origin = 'Brazil', slug = 'midnight-sugar-free-brazil-64-100g' WHERE id = 83;
UPDATE products SET name = 'Amber Single Origin - Ghana 67%', origin = 'Ghana', slug = 'amber-single-origin-ghana-67-110g' WHERE id = 84;
UPDATE products SET name = 'Luxe Seasonal & Limited Edition - Mexico 70%', origin = 'Mexico', slug = 'luxe-seasonal-and-limited-edition-mexico-70-70g' WHERE id = 85;
UPDATE products SET name = 'Golden Gift Boxes - Madagascar 73%', origin = 'Madagascar', slug = 'golden-gift-boxes-madagascar-73-80g' WHERE id = 86;
UPDATE products SET name = 'Estate Spreads & Creams - Madagascar 76%', origin = 'Madagascar', slug = 'estate-spreads-and-creams-madagascar-76-90g' WHERE id = 87;
UPDATE products SET name = 'Vintage Raw & Organic - Vietnam 79%', origin = 'Vietnam', slug = 'vintage-raw-and-organic-vietnam-79-100g' WHERE id = 88;
UPDATE products SET name = 'Signature Chocolate-Covered Nuts - Brazil 82%', origin = 'Brazil', slug = 'signature-chocolate-covered-nuts-brazil-82-110g' WHERE id = 89;
UPDATE products SET name = 'Artisan Chocolate Bars - Colombia 85%', origin = 'Colombia', slug = 'artisan-chocolate-bars-colombia-85-70g' WHERE id = 90;
UPDATE products SET name = 'Velvety Dark Chocolate - Tanzania 88%', origin = 'Tanzania', slug = 'velvety-dark-chocolate-tanzania-88-80g' WHERE id = 91;
UPDATE products SET name = 'Roasted Milk Chocolate - Mexico 91%', origin = 'Mexico', slug = 'roasted-milk-chocolate-mexico-91-90g' WHERE id = 92;
UPDATE products SET name = 'Hand-Tempered White Chocolate - Colombia 94%', origin = 'Colombia', slug = 'hand-tempered-white-chocolate-colombia-94-100g' WHERE id = 93;
UPDATE products SET name = 'Single-Harvest Ruby Chocolate - Dominican Republic 57%', origin = 'Dominican Republic', slug = 'single-harvest-ruby-chocolate-dominican-republic-57-110g' WHERE id = 94;
UPDATE products SET name = 'Stone-Ground Filled & Pralines - Dominican Republic 60%', origin = 'Dominican Republic', slug = 'stone-ground-filled-and-pralines-dominican-republic-60-70g' WHERE id = 95;
UPDATE products SET name = 'Silk-Smooth Drinking Chocolate - Brazil 63%', origin = 'Brazil', slug = 'silk-smooth-drinking-chocolate-brazil-63-80g' WHERE id = 96;
UPDATE products SET name = 'Cacao-Rich Vegan & Dairy-Free - Brazil 66%', origin = 'Brazil', slug = 'cacao-rich-vegan-and-dairy-free-brazil-66-90g' WHERE id = 97;
UPDATE products SET name = 'Midnight Sugar-Free - Mexico 69%', origin = 'Mexico', slug = 'midnight-sugar-free-mexico-69-100g' WHERE id = 98;
UPDATE products SET name = 'Amber Single Origin - Tanzania 72%', origin = 'Tanzania', slug = 'amber-single-origin-tanzania-72-110g' WHERE id = 99;
UPDATE products SET name = 'Luxe Seasonal & Limited Edition - Ghana 75%', origin = 'Ghana', slug = 'luxe-seasonal-and-limited-edition-ghana-75-70g' WHERE id = 100;

COMMIT;

SET SQL_SAFE_UPDATES = 1;
